#include <stdio.h>
#include <stdlib.h>

int main() {
  int *evens, datacount = 0, i = 2, k = 1;
  evens = malloc(sizeof(int) * datacount);

  while (i < 4000000) {
    if (i % 2 == 0) {
      datacount++;
      evens[datacount] = i;
      printf("%d\n\n", i);
    }

    int q = i;
    i = i + k;
    k = q;
  }

  int sum = 0;

  for (int j = 0; j <= datacount; j++) {
    sum = sum + evens[j];
  }

  printf("Sum: %d\n\n", sum);

  return 0;
}

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
